spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: project
    profiles:
        active: dev
    security: 
        oauth2: 
            client: 
                registration: 
                    google: 
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        scope: openid, profile, email
                    github:
                        client-id: ${GITHUB_CLIENT_ID}
                        client-secret: ${GITHUB_CLIENT_SECRET}
                        scope: read:user, user:email

admin:
    bootstrap:
        fullname: ${ADMIN_FULLNAME}
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
        email: ${ADMIN_EMAIL}
        roles: ${ADMIN_ROLES}

jwt: 
    issuer: ${issuer}
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration: 3600
    refresh-token-expiration: 604800

cors: 
    allowed-origins: ${ALLOWED_ORIGINS}
    allowed-methods: ${ALLOWED_METHODS}
    allowed-headers: ${ALLOWED_HEADERS}
    allow-credentials: ${ALLOW_CREDENTIALS}
    frontend-callback-url: ${FRONTEND_URL_CALLBACK}

# ```
# Ưu tiên từ CAO → THẤP:
# ──────────────────────
# 1. Command line arguments (--server.port=9090)
# 2. Environment variables (SERVER_PORT=9090)
# 3. application-{profile}.properties
# 4. application.properties
# 5. Default values trong code
# ```